
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'ru' | 'fr';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    home: 'Home',
    deals: 'Deals',
    account: 'Account',
    mode: 'Mode',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    heroTitle: 'Exclusive Swiss Deals for Khaleej Travelers',
    heroSubtitle: 'Your trusted guide for exclusive offers',
    unlockOffers: 'Unlock Exclusive Swiss Offers',
    hotelsTitle: "Luxury Hotels",
    hotelsSubtitle: "Memorable Stays",
    hotelsBadge: "Up to -40%",
    carsTitle: "Prestige Cars",
    carsSubtitle: "Partners: Sixt & Prestige",
    carsBadge: "Exclusive Rates",
    experiencesTitle: "Leisure & Discovery",
    experiencesSubtitle: "Museums, Watches & Fun",
    experiencesBadge: "Tourism",
    transfersTitle: "Chauffeur & Transfers",
    transfersSubtitle: "Airport & City",
    transfersBadge: "Best Price",
    vipOnly: "VIP ONLY",
    vipSubtitle: "Preferential rates for members",
    seeAll: "See all",
    todaysDeals: "CHOOSE YOUR LOCATION",
    testimonials: "Traveler Reviews",
    verifiedMember: "Verified Member",
    promoTitle: "100 CHF discount on your first booking",
    joinSave: "Join & Save",
    searchPlaceholder: "Search...",
    discover: "Discover",
    swissConcierge: "Swiss Concierge",
    guideToSwiss: "Your guide to Switzerland",
    bestRentalDeals: "Best Rental Deals",
    bestRentalDealsSubtitle: "Drive the best for less",
    generalExperiencesTitle: "Unforgettable Experiences",
    generalExperiencesSubtitle: "Discover Switzerland",
    transferTitle: "Premium Airport Transfers",
    transferSubtitle: "Seamless & luxury travel from arrival to your destination. Best rates guaranteed.",
    bookTransfer: "Book Transfer",
    klookBannerTitle: "Best Price Guaranteed with Klook",
    klookBannerSubtitle: "Book your stay via our official partner and save up to 60%",
    klookButton: "Check Rates",
    instantConfirmation: "Instant Confirmation",
    bookOnKlook: "Book on Klook",
    viewFullInventory: "View Full Inventory",
    cantFindHotel: "Can't find the hotel you're looking for?",
    searchOnKlook: "Search all hotels on Klook",
    pickupLocation: "Pickup Location",
    dropoffLocation: "Destination",
    oneWay: "One-way",
    roundTrip: "Round-trip",
    findTransfer: "Find Transfer",
    passengers: "Passengers",
    fixedPrice: "Fixed Price",
    freeCancellation: "Free Cancellation",
    professionalDriver: "Pro Driver",
    selectDate: "Select Date",
    selectTime: "Select Time",
    transferPageTitle: "Airport Transfers & Chauffeur",
    transferPageSubtitle: "Reliable, luxurious, and fixed-price transfers across Switzerland.",
    ourFleet: "Our Fleet",
    esimTitle: "Travel Connected",
    esimSubtitle: "Instant internet access in Switzerland & Europe.",
    selectDestination: "Select Destination",
    dataPlans: "Data Plans",
    buyEsim: "Buy my eSIM",
    instantActivation: "Instant Activation",
    globalCoverage: "200+ Destinations",
    bestRates: "18% Cheaper",
    summary: "Summary",
    plan: "Plan",
    total: "Total",
  },
  ar: {
    home: 'الرئيسية',
    deals: 'عروض',
    account: 'حسابي',
    mode: 'الوضع',
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    heroTitle: 'عروض سويسرية حصرية للمسافرين الخليجيين',
    heroSubtitle: 'دليلك الموثوق للعروض الحصرية',
    unlockOffers: 'اكتشف العروض الحصرية',
    hotelsTitle: "فنادق فاخرة",
    hotelsSubtitle: "إقامات لا تنسى",
    hotelsBadge: "خصم يصل لـ 40%",
    carsTitle: "سيارات فارهة",
    carsSubtitle: "شراكة مع Sixt و Prestige",
    carsBadge: "أسعار حصرية",
    experiencesTitle: "ترفيه واكتشاف",
    experiencesSubtitle: "متاحف، ساعات ومرح",
    experiencesBadge: "سياحة",
    transfersTitle: "سائق وتوصيل",
    transfersSubtitle: "المطار والمدينة",
    transfersBadge: "أفضل سعر",
    vipOnly: "للشخصيات المهمة",
    vipSubtitle: "أسعار تفضيلية للأعضاء",
    seeAll: "عرض الكل",
    todaysDeals: "اختر وجهتك",
    testimonials: "آراء المسافرين",
    verifiedMember: "عضو موثوق",
    promoTitle: "خصم 100 فرنك على حجزك الأول",
    joinSave: "انضم ووفر",
    searchPlaceholder: "بحث...",
    discover: "اكتشف",
    swissConcierge: "كونسيرج سويسري",
    guideToSwiss: "دليلك إلى سويسرا",
    bestRentalDeals: "أفضل عروض التأجير",
    bestRentalDealsSubtitle: "قد الأفضل بأقل الأسعار",
    generalExperiencesTitle: "تجربة لا تنسى",
    generalExperiencesSubtitle: "اكتشف سويسرا",
    transferTitle: "نقل المطار الفاخر",
    transferSubtitle: "سفر سلس وفاخر من الوصول إلى وجهتك. أفضل الأسعار مضمونة.",
    bookTransfer: "حجز نقل",
    klookBannerTitle: "أفضل سعر مضمون مع Klook",
    klookBannerSubtitle: "احجز إقامتك عبر شريكنا الرسمي ووفر حتى 60٪",
    klookButton: "تحقق من الأسعار",
    instantConfirmation: "تأكيد فوري",
    bookOnKlook: "احجز على Klook",
    viewFullInventory: "عرض المخزون الكامل",
    cantFindHotel: "لا تجد الفندق الذي تبحث عنه؟",
    searchOnKlook: "ابحث عن جميع الفنادق على Klook",
    pickupLocation: "مكان الاخذ",
    dropoffLocation: "الوجهة",
    oneWay: "ذهاب فقط",
    roundTrip: "ذهاب وعودة",
    findTransfer: "بحث عن نقل",
    passengers: "ركاب",
    fixedPrice: "سعر ثابت",
    freeCancellation: "إلغاء مجاني",
    professionalDriver: "سائق محترف",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    transferPageTitle: "نقل المطار وسائق خاص",
    transferPageSubtitle: "نقل موثوق وفاخر وبسعر ثابت في جميع أنحاء سويسرا.",
    ourFleet: "أسطولنا",
    esimTitle: "سافر متصلاً",
    esimSubtitle: "إنترنت فوري في سويسرا وأوروبا.",
    selectDestination: "اختر الوجهة",
    dataPlans: "باقات البيانات",
    buyEsim: "شراء شريحة إلكترونية",
    instantActivation: "تفعيل فوري",
    globalCoverage: "200+ وجهة",
    bestRates: "18% أرخص",
    summary: "ملخص",
    plan: "خطة",
    total: "المجموع",
  },
  ru: {
    home: 'Главная',
    deals: 'Акции',
    account: 'Аккаунт',
    mode: 'Режим',
    goodMorning: 'Доброе утро',
    goodAfternoon: 'Добрый день',
    goodEvening: 'Добрый вечер',
    heroTitle: 'Эксклюзивные предложения в Швейцарии',
    heroSubtitle: 'Ваш надежный гид по эксклюзивным предложениям',
    unlockOffers: 'Открыть предложения',
    hotelsTitle: "Роскошные отели",
    hotelsSubtitle: "Незабываемый отдых",
    hotelsBadge: "Скидки до -40%",
    carsTitle: "Престижные авто",
    carsSubtitle: "Партнеры: Sixt & Prestige",
    carsBadge: "Эксклюзивные тарифы",
    experiencesTitle: "Досуг и Открытия",
    experiencesSubtitle: "Музеи, Часы и Развлечения",
    experiencesBadge: "Туризм",
    transfersTitle: "Трансферы и Шофер",
    transfersSubtitle: "Аэропорт и Город",
    transfersBadge: "Лучшая цена",
    vipOnly: "VIP",
    vipSubtitle: "Специальные тарифы для участников",
    seeAll: "Показать все",
    todaysDeals: "ВЫБЕРИТЕ МЕСТОПОЛОЖЕНИЕ",
    testimonials: "Отзывы путешественников",
    verifiedMember: "Проверенный участник",
    promoTitle: "Скидка 100 CHF на первое бронирование",
    joinSave: "Присоединиться",
    searchPlaceholder: "Поиск...",
    discover: "Обзор",
    swissConcierge: "Швейцарский консьерж",
    guideToSwiss: "Ваш гид по Швейцарии",
    bestRentalDeals: "Лучшие предложения аренды",
    bestRentalDealsSubtitle: "Лучшие авто по лучшим ценам",
    generalExperiencesTitle: "Незабываемые впечатления",
    generalExperiencesSubtitle: "Откройте Швейцарию",
    transferTitle: "Премиум трансферы из аэропорта",
    transferSubtitle: "Безупречное путешествие от прибытия до места назначения.",
    bookTransfer: "Заказать трансфер",
    klookBannerTitle: "Гарантия лучшей цены с Klook",
    klookBannerSubtitle: "Бронируйте через нашего партнера и экономьте до 60%",
    klookButton: "Проверить цены",
    instantConfirmation: "Мгновенное подтверждение",
    bookOnKlook: "Бронировать на Klook",
    viewFullInventory: "Посмотреть все отели",
    cantFindHotel: "Не нашли нужный отель?",
    searchOnKlook: "Искать все отели на Klook",
    pickupLocation: "Место посадки",
    dropoffLocation: "Назначение",
    oneWay: "В одну сторону",
    roundTrip: "Туда и обратно",
    findTransfer: "Найти трансфер",
    passengers: "Пассажиры",
    fixedPrice: "Фикс. цена",
    freeCancellation: "Беспл. отмена",
    professionalDriver: "Проф. водитель",
    selectDate: "Дата",
    selectTime: "Время",
    transferPageTitle: "Трансферы из аэропорта",
    transferPageSubtitle: "Надежные, роскошные трансферы с фиксированной ценой по всей Швейцарии.",
    ourFleet: "Наш автопарк",
    esimTitle: "Оставайтесь на связи",
    esimSubtitle: "Мгновенный интернет в Швейцарии и Европе.",
    selectDestination: "Выберите направление",
    dataPlans: "Тарифы данных",
    buyEsim: "Купить eSIM",
    instantActivation: "Мгновенная активация",
    globalCoverage: "200+ стран",
    bestRates: "На 18% дешевле",
    summary: "Итог",
    plan: "Тариф",
    total: "Итого",
  },
  fr: {
    home: 'Accueil',
    deals: 'Offres',
    account: 'Compte',
    mode: 'Mode',
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    heroTitle: 'Offres Suisses Exclusives pour Voyageurs',
    heroSubtitle: 'Votre guide de confiance pour des offres exclusives',
    unlockOffers: 'Voir les offres exclusives',
    hotelsTitle: "Hôtels d'exception",
    hotelsSubtitle: "Séjours mémorables",
    hotelsBadge: "Jusqu'à -40%",
    carsTitle: "Voitures de prestige",
    carsSubtitle: "Partenaires: Sixt & Prestige",
    carsBadge: "Tarifs Exclusifs",
    experiencesTitle: "Loisirs & Découvertes",
    experiencesSubtitle: "Musées, Montres & Fun",
    experiencesBadge: "Tourisme",
    transfersTitle: "Transferts & Chauffeurs",
    transfersSubtitle: "Aéroport & Ville",
    transfersBadge: "Meilleur Prix",
    vipOnly: "VIP UNIQUEMENT",
    vipSubtitle: "Tarifs préférentiels réservés aux membres",
    seeAll: "Tout voir",
    todaysDeals: "CHOISISSEZ VOTRE DESTINATION",
    testimonials: "Avis Voyageurs",
    verifiedMember: "Membre vérifié",
    promoTitle: "100 CHF de réduction sur votre première réservation",
    joinSave: "Rejoindre & Économiser",
    searchPlaceholder: "Rechercher...",
    discover: "Découvrir",
    swissConcierge: "Conciergerie Suisse",
    guideToSwiss: "Votre guide en Suisse",
    bestRentalDeals: "Meilleures Offres Location",
    bestRentalDealsSubtitle: "Roulez le meilleur pour moins",
    generalExperiencesTitle: "Expériences Inoubliables",
    generalExperiencesSubtitle: "Découvrez la Suisse",
    transferTitle: "Transferts Aéroport Premium",
    transferSubtitle: "Voyagez sans encombre de l'arrivée à votre destination. Meilleurs tarifs garantis.",
    bookTransfer: "Réserver un Transfert",
    klookBannerTitle: "Meilleur Prix Garanti avec Klook",
    klookBannerSubtitle: "Réservez via notre partenaire officiel et économisez jusqu'à 60%",
    klookButton: "Voir les tarifs",
    instantConfirmation: "Confirmation immédiate",
    bookOnKlook: "Réserver sur Klook",
    viewFullInventory: "Voir tout l'inventaire",
    cantFindHotel: "Vous ne trouvez pas votre hôtel ?",
    searchOnKlook: "Chercher parmi 10 000+ hôtels",
    pickupLocation: "Lieu de prise en charge",
    dropoffLocation: "Destination",
    oneWay: "Aller simple",
    roundTrip: "Aller-retour",
    findTransfer: "Rechercher un transfert",
    passengers: "Passagers",
    fixedPrice: "Prix fixe",
    freeCancellation: "Annulation gratuite",
    professionalDriver: "Chauffeur pro",
    selectDate: "Date",
    selectTime: "Heure",
    transferPageTitle: "Transferts Aéroport & Chauffeur",
    transferPageSubtitle: "Transferts fiables, luxueux et à prix fixe dans toute la Suisse.",
    ourFleet: "Notre Flotte",
    esimTitle: "Voyagez Connecté",
    esimSubtitle: "Internet instantané en Suisse et en Europe.",
    selectDestination: "Choisir la destination",
    dataPlans: "Forfaits Données",
    buyEsim: "Acheter mon eSIM",
    instantActivation: "Activation instantanée",
    globalCoverage: "200+ destinations",
    bestRates: "18% moins cher",
    summary: "Récapitulatif",
    plan: "Forfait",
    total: "Total",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('khaleex_lang') as Language;
    if (savedLang && ['en', 'ar', 'ru', 'fr'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('khaleex_lang', language);
    
    // Handle RTL/LTR
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    
    // Optional: Add a class to body for specific styling if needed
    if (language === 'ar') {
        document.body.classList.add('rtl');
    } else {
        document.body.classList.remove('rtl');
    }

  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
