import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar' | 'ru' | 'fr';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    home: 'Home',
    deals: 'Deals',
    account: 'Account',
    mode: 'Mode',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    heroTitle: 'Exclusive Swiss Deals for Khaleej Travelers',
    heroSubtitle: 'Your trusted guide for exclusive offers',
    unlockOffers: 'Unlock Exclusive Swiss Offers',
    hotelsTitle: "Luxury Hotels",
    hotelsSubtitle: "Memorable Stays",
    hotelsBadge: "Up to -40%",
    carsTitle: "Prestige Cars",
    carsSubtitle: "Partners: Sixt & Prestige",
    carsBadge: "Exclusive Rates",
    experiencesTitle: "Leisure & Discovery",
    experiencesSubtitle: "Museums, Watches & Fun",
    experiencesBadge: "Tourism",
    transfersTitle: "Chauffeur & Transfers",
    transfersSubtitle: "Airport & City",
    transfersBadge: "Best Price",
    vipOnly: "VIP ONLY",
    vipSubtitle: "Preferential rates for members",
    seeAll: "See all",
    todaysDeals: "CHOOSE YOUR LOCATION",
    testimonials: "Traveler Reviews",
    verifiedMember: "Verified Member",
    promoTitle: "100 CHF discount on your first booking",
    joinSave: "Join & Save",
    searchPlaceholder: "Search...",
    discover: "Discover",
    swissConcierge: "Swiss Concierge",
    guideToSwiss: "Your guide to Switzerland",
    bestRentalDeals: "Best Rental Deals",
    bestRentalDealsSubtitle: "Drive the best for less",
    generalExperiencesTitle: "Experiences",
    generalExperiencesSubtitle: "Discover Switzerland",
    transferTitle: "Premium Airport Transfers",
    transferSubtitle: "Seamless & luxury travel from arrival to your destination. Best rates guaranteed.",
    bookTransfer: "Book Transfer",
    klookBannerTitle: "Best Price Guaranteed with Klook",
    klookBannerSubtitle: "Book your stay via our official partner and save up to 60%",
    klookButton: "Check Rates",
    instantConfirmation: "Instant Confirmation",
    bookOnKlook: "Book on Klook",
    viewFullInventory: "View Full Inventory",
    cantFindHotel: "Can't find the hotel you're looking for?",
    searchOnKlook: "Search all hotels on Klook",
    pickupLocation: "Pickup Location",
    dropoffLocation: "Destination",
    oneWay: "One-way",
    roundTrip: "Round-trip",
    findTransfer: "Find Transfer",
    passengers: "Passengers",
    fixedPrice: "Fixed Price",
    freeCancellation: "Free Cancellation",
    professionalDriver: "Pro Driver",
    selectDate: "Select Date",
    selectTime: "Select Time",
    transferPageTitle: "Airport Transfers & Chauffeur",
    transferPageSubtitle: "Reliable, luxurious, and fixed-price transfers across Switzerland.",
    ourFleet: "Our Fleet",
    esimTitle: "Travel Connected",
    esimSubtitle: "Instant internet access in Switzerland & Europe.",
    selectDestination: "Select Destination",
    dataPlans: "Data Plans",
    buyEsim: "Buy my eSIM",
    instantActivation: "Instant Activation",
    globalCoverage: "200+ Destinations",
    bestRates: "18% Cheaper",
    summary: "Summary",
    plan: "Plan",
    total: "Total",

    // New keys
    exclusive: "Exclusive",
    comingSoon: "Coming Soon",
    contactOnWhatsApp: "Contact on WhatsApp",
    whatsApp: "WhatsApp",
    whatsAppMessage: "Hello Khaleex, I would like to get information about your VIP services.",
    needHelp: "Need help?",
    vipSupport: "24/7 VIP Support",
    contactUs: "Contact Us",
    prestigeCars: "Prestige Cars",
    admin: "Admin",
    loadingVehicles: "Loading vehicles...",
    errorOccurred: "An error occurred",
    errorLoadingVehicles: "Could not load vehicles. Please try again later.",
    noVehiclesFound: "No vehicles match your criteria.",
    realTimeVehicles: "Vehicles available in real time.",
    leisureAndDiscoveries: "Leisure & Discoveries",
    experiencesPageSubtitle: "A selection of cultural and tourist activities to enrich your stay in Switzerland. For our exclusive services (Jets, Chefs...), visit the VIP section.",
    loadingActivities: "Loading activities...",
    errorLoadingExperiences: "Could not load experiences. Please try again later.",
    from: "from",
    perNight: "/night",
    showDetails: "Show details",
    hideDetails: "Hide details",
    changeImage: "Change image",
    addImage: "Add image",
    imageNotAvailable: "Image not available",
    priceComparator: "Price Comparison",
    bestOffer: "Best Offer",
    seats: "Seats",
    perDay: "/day",
    book: "Book",
    noImage: "No image",
    changeImageShort: "Change",
    rentalDetails: "Your Rental Details",
    forVehicle: "For the vehicle",
    pickupDate: "Pickup Date",
    returnDate: "Return Date",
    pickupLocationLabel: "Pickup Location",
    pickupLocationPlaceholder: "e.g., Geneva Airport",
    bookOnPartnerSite: "Book on partner's site",
    redirectPartnerCar: "You will be redirected to our partner's site to finalize the rental.",
    stayDetails: "Your Stay Details",
    forHotel: "For the hotel",
    checkInDate: "Check-in Date",
    checkOutDate: "Check-out Date",
    travelersCount: "Number of travelers",
    finalizeBooking: "Finalize booking",
    redirectPartnerHotel: "You will be redirected to our partner to securely finalize your booking.",
    myAccount: "My Account",
    welcomeToKhaleex: "Welcome to Khaleex",
    loginToAccessVip: "Log in to access your VIP profile and unlock exclusive offers.",
    loginRegister: "Log In / Sign Up",
    byContinuingYouAgree: "By continuing, you agree to our terms of service.",
    termsShort: "ToS",
    privacyShort: "Privacy",
    personalInfo: "Personal Information",
    paymentMethods: "Payment Methods",
    notifications: "Notifications",
    securityAndLogin: "Security & Login",
    helpAndSupport: "Help & Support",
    legalAndCompliance: "Legal & Compliance",
    legalNotice: "Legal Notice",
    logout: "Log Out",
    exclusiveServicesGeneva: "Exclusive Services in Geneva",
    rentPrestigeCar: "Rent a prestige car",
    rentPrestigeCarSubtitle: "Discover our exclusive fleet and enjoy the road in style.",
    rentalPartners: "Our rental partners in Geneva",
    exclusiveAtHomeServices: "Exclusive At-Home Services",
    excursionsChamonix: "Excursions in Chamonix",
    excursionsChamonixSubtitle: "Discover unique experiences at the foot of Mont Blanc, inspired by the best offers on Airbnb and Klook. Book easily via our WhatsApp concierge service.",
    reviews: "reviews",
    inspiredBy: "Inspired by",
    fromPerPerson: "/pers.",
    filters: "Filters",
    maxPricePerNight: "Maximum price per night",
    stars: "Stars",
    amenities: "Amenities",
    reset: "Reset",
    apply: "Apply",
    serviceDetails: "Your Service Details",
    forService: "For the service",
    date: "Date",
    startTime: "Start Time",
    durationHours: "Duration (in hours)",
    redirectPartnerService: "You will be redirected to finalize your exclusive booking.",
    publicPrice: "Public Price",
    vipPrice: "VIP Price",
    vipServices: "VIP Services",
    becomeVipMember: "Become an Annual VIP Member",
    vipMemberDescription: "Save up to 30% on all our premium services: Private Jets, Villas, Helicopters, and Chefs.",
    profitableFromFirstFlight: "Profitable from the first flight.",
    subscribeAnnual: "Subscribe (1200 CHF/year)",
    exclusiveServicesOfTheMoment: "Exclusive Services of the Moment",
    vipDisclaimer: "*VIP prices are guaranteed for Khaleex Black card holders. Bookings are subject to availability and confirmation by our concierge service.",
    legal: "Legal",
    support: "Support",
    contactEmailLabel: "Email",
    exclusivePartner: "Exclusive Partner",
    proChauffeurs: "Pro Chauffeurs",
    mercedesAndBmw: "Mercedes & BMW",
    meetAndGreet: "Meet & Greet",
    vipTransfer: "VIP Transfer",
    suitcases: "Suitcases",
    selectCountryPlaceholder: "Select a country...",
    expediaPartner: "Expedia Partner",
    bestRatesGuaranteed: "Best Rates Guaranteed",
    luxuryHotelsAndSki: "Luxury & Ski Hotels",
    luxuryHotelsAndSkiSubtitle: "Select your destination to discover our exclusive partner hotels. Real-time comparison.",
    loadingHotels: "Searching for the best hotels...",
    noHotelsAvailable: "No hotels available for this destination.",
    serviceUnavailable: "Service temporarily unavailable.",
    chooseAnotherDestination: "Choose another destination",
    noImageAvailable: "No image",
    viewPrices: "View prices",
    pleaseSelectDestination: "Please select a destination above",
    checkIn: "Check-in",
    checkOut: "Check-out",
    loadingRates: "Searching for the best rates...",
    ratesUnavailable: "Prices not available for these dates.",
    bookOnExpedia: "Book on Expedia / Hotels.com",
    bookingRedirectDisclaimer: "By booking via this link, you will be redirected to our partners with dates from {checkInDate} to {checkOutDate}.",
    carFilters: "Vehicle Filters",
    maxPricePerDay: "Maximum price per day",
    transmission: "Transmission",
    make: "Make",
    auto: "Auto",
    manual: "Manual",
    destination: "Destination",
    countrySwitzerland: "Switzerland",
    countryEurope: "Europe (Regional)",
    countryFrance: "France",
    countryUae: "UAE",
    countryUsa: "USA",
    days7: "7 Days",
    days15: "15 Days",
    days30: "30 Days",
    unlimited: "Unlimited",
    luxuryHotelsAndAccommodations: "Luxury Hotels & Accommodations",
    stayInGenevaBest: "Stay in Geneva's finest establishments.",
    exclusiveExperiences: "Exclusive Experiences",
    exclusiveExperiencesSubtitle: "Unforgettable moments, VIP access.",
  },
  ar: {
    home: 'الرئيسية',
    deals: 'عروض',
    account: 'حسابي',
    mode: 'الوضع',
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    heroTitle: 'عروض سويسرية حصرية للمسافرين الخليجيين',
    heroSubtitle: 'دليلك الموثوق للعروض الحصرية',
    unlockOffers: 'اكتشف العروض الحصرية',
    hotelsTitle: "فنادق فاخرة",
    hotelsSubtitle: "إقامات لا تنسى",
    hotelsBadge: "خصم يصل لـ 40%",
    carsTitle: "سيارات فارهة",
    carsSubtitle: "شراكة مع Sixt و Prestige",
    carsBadge: "أسعار حصرية",
    experiencesTitle: "ترفيه واكتشاف",
    experiencesSubtitle: "متاحف، ساعات ومرح",
    experiencesBadge: "سياحة",
    transfersTitle: "سائق وتوصيل",
    transfersSubtitle: "المطار والمدينة",
    transfersBadge: "أفضل سعر",
    vipOnly: "للشخصيات المهمة",
    vipSubtitle: "أسعار تفضيلية للأعضاء",
    seeAll: "عرض الكل",
    todaysDeals: "اختر وجهتك",
    testimonials: "آراء المسافرين",
    verifiedMember: "عضو موثوق",
    promoTitle: "خصم 100 فرنك على حجزك الأول",
    joinSave: "انضم ووفر",
    searchPlaceholder: "بحث...",
    discover: "اكتشف",
    swissConcierge: "كونسيرج سويسري",
    guideToSwiss: "دليلك إلى سويسرا",
    bestRentalDeals: "أفضل عروض التأجير",
    bestRentalDealsSubtitle: "قد الأفضل بأقل الأسعار",
    generalExperiencesTitle: "تجارب",
    generalExperiencesSubtitle: "اكتشف سويسرا",
    transferTitle: "نقل المطار الفاخر",
    transferSubtitle: "سفر سلس وفاخر من الوصول إلى وجهتك. أفضل الأسعار مضمونة.",
    bookTransfer: "حجز نقل",
    klookBannerTitle: "أفضل سعر مضمون مع Klook",
    klookBannerSubtitle: "احجز إقامتك عبر شريكنا الرسمي ووفر حتى 60٪",
    klookButton: "تحقق من الأسعار",
    instantConfirmation: "تأكيد فوري",
    bookOnKlook: "احجز على Klook",
    viewFullInventory: "عرض المخزون الكامل",
    cantFindHotel: "لا تجد الفندق الذي تبحث عنه؟",
    searchOnKlook: "ابحث عن جميع الفنادق على Klook",
    pickupLocation: "مكان الاخذ",
    dropoffLocation: "الوجهة",
    oneWay: "ذهاب فقط",
    roundTrip: "ذهاب وعودة",
    findTransfer: "بحث عن نقل",
    passengers: "ركاب",
    fixedPrice: "سعر ثابت",
    freeCancellation: "إلغاء مجاني",
    professionalDriver: "سائق محترف",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    transferPageTitle: "نقل المطار وسائق خاص",
    transferPageSubtitle: "نقل موثوق وفاخر وبسعر ثابت في جميع أنحاء سويسرا.",
    ourFleet: "أسطولنا",
    esimTitle: "سافر متصلاً",
    esimSubtitle: "إنترنت فوري في سويسرا وأوروبا.",
    selectDestination: "اختر الوجهة",
    dataPlans: "باقات البيانات",
    buyEsim: "شراء شريحة إلكترونية",
    instantActivation: "تفعيل فوري",
    globalCoverage: "200+ وجهة",
    bestRates: "18% أرخص",
    summary: "ملخص",
    plan: "خطة",
    total: "المجموع",

    // New keys
    exclusive: "حصري",
    comingSoon: "قريبا",
    contactOnWhatsApp: "اتصل على WhatsApp",
    whatsApp: "WhatsApp",
    whatsAppMessage: "مرحبًا خليج، أود الحصول على معلومات حول خدماتكم لكبار الشخصيات.",
    needHelp: "تحتاج مساعدة؟",
    vipSupport: "دعم VIP 24/7",
    contactUs: "اتصل بنا",
    prestigeCars: "سيارات فارهة",
    admin: "مشرف",
    loadingVehicles: "جاري تحميل المركبات...",
    errorOccurred: "حدث خطأ",
    errorLoadingVehicles: "تعذر تحميل المركبات. يرجى المحاولة مرة أخرى لاحقًا.",
    noVehiclesFound: "لا توجد مركبات تطابق معاييرك.",
    realTimeVehicles: "المركبات متاحة في الوقت الفعلي.",
    leisureAndDiscoveries: "الترفيه والاكتشافات",
    experiencesPageSubtitle: "مجموعة مختارة من الأنشطة الثقافية والسياحية لإثراء إقامتك في سويسرا. لخدماتنا الحصرية (طائرات، طهاة...)، قم بزيارة قسم كبار الشخصيات.",
    loadingActivities: "جاري تحميل الأنشطة...",
    errorLoadingExperiences: "تعذر تحميل التجارب. يرجى المحاولة مرة أخرى لاحقًا.",
    from: "ابتداءً من",
    perNight: "/ليلة",
    showDetails: "عرض التفاصيل",
    hideDetails: "إخفاء التفاصيل",
    changeImage: "تغيير الصورة",
    addImage: "إضافة صورة",
    imageNotAvailable: "الصورة غير متوفرة",
    priceComparator: "مقارنة الأسعار",
    bestOffer: "أفضل عرض",
    seats: "مقاعد",
    perDay: "/يوم",
    book: "احجز",
    noImage: "لا توجد صورة",
    changeImageShort: "تغيير",
    rentalDetails: "تفاصيل الإيجار",
    forVehicle: "للمركبة",
    pickupDate: "تاريخ الاستلام",
    returnDate: "تاريخ التسليم",
    pickupLocationLabel: "مكان الاستلام",
    pickupLocationPlaceholder: "مثال: مطار جنيف",
    bookOnPartnerSite: "الحجز على موقع الشريك",
    redirectPartnerCar: "سيتم إعادة توجيهك إلى موقع شريكنا لإنهاء عملية الإيجار.",
    stayDetails: "تفاصيل إقامتك",
    forHotel: "للفندق",
    checkInDate: "تاريخ الوصول",
    checkOutDate: "تاريخ المغادرة",
    travelersCount: "عدد المسافرين",
    finalizeBooking: "إتمام الحجز",
    redirectPartnerHotel: "سيتم إعادة توجيهك إلى شريكنا لإنهاء حجزك بأمان.",
    myAccount: "حسابي",
    welcomeToKhaleex: "مرحبًا بك في خليج",
    loginToAccessVip: "سجل الدخول للوصول إلى ملفك الشخصي VIP وفتح العروض الحصرية.",
    loginRegister: "تسجيل الدخول / إنشاء حساب",
    byContinuingYouAgree: "من خلال المتابعة، فإنك توافق على شروط الخدمة الخاصة بنا.",
    termsShort: "الشروط",
    privacyShort: "الخصوصية",
    personalInfo: "المعلومات الشخصية",
    paymentMethods: "طرق الدفع",
    notifications: "الإشعارات",
    securityAndLogin: "الأمان وتسجيل الدخول",
    helpAndSupport: "المساعدة والدعم",
    legalAndCompliance: "قانوني وامتثال",
    legalNotice: "إشعار قانوني",
    logout: "تسجيل الخروج",
    exclusiveServicesGeneva: "خدمات حصرية في جنيف",
    rentPrestigeCar: "استأجر سيارة فارهة",
    rentPrestigeCarSubtitle: "اكتشف أسطولنا الحصري واستمتع بالطريق بأناقة.",
    rentalPartners: "شركاؤنا في الإيجار في جنيف",
    exclusiveAtHomeServices: "خدمات حصرية في المنزل",
    excursionsChamonix: "رحلات في شامونيه",
    excursionsChamonixSubtitle: "اكتشف تجارب فريدة عند سفح مون بلان، مستوحاة من أفضل العروض على Airbnb و Klook. احجز بسهولة عبر خدمة الكونسيرج على WhatsApp.",
    reviews: "تقييمات",
    inspiredBy: "مستوحى من",
    fromPerPerson: "/للشخص",
    filters: "الفلاتر",
    maxPricePerNight: "أقصى سعر لليلة",
    stars: "النجوم",
    amenities: "وسائل الراحة",
    reset: "إعادة تعيين",
    apply: "تطبيق",
    serviceDetails: "تفاصيل خدمتك",
    forService: "للخدمة",
    date: "التاريخ",
    startTime: "وقت البدء",
    durationHours: "المدة (بالساعات)",
    redirectPartnerService: "سيتم إعادة توجيهك لإنهاء حجزك الحصري.",
    publicPrice: "السعر العام",
    vipPrice: "سعر VIP",
    vipServices: "خدمات VIP",
    becomeVipMember: "كن عضوًا سنويًا في VIP",
    vipMemberDescription: "وفر حتى 30٪ على جميع خدماتنا المتميزة: طائرات خاصة، فيلات، طائرات هليكوبتر، وطهاة.",
    profitableFromFirstFlight: "مربحة من أول رحلة.",
    subscribeAnnual: "اشترك (1200 فرنك سويسري/سنة)",
    exclusiveServicesOfTheMoment: "خدمات حصرية في الوقت الحالي",
    vipDisclaimer: "*أسعار VIP مضمونة لحاملي بطاقة خليج السوداء. تخضع الحجوزات للتوافر والتأكيد من قبل خدمة الكونسيرج لدينا.",
    legal: "قانوني",
    support: "الدعم",
    contactEmailLabel: "البريد الإلكتروني",
    exclusivePartner: "شريك حصري",
    proChauffeurs: "سائقون محترفون",
    mercedesAndBmw: "مرسيدس و BMW",
    meetAndGreet: "استقبال وتحية",
    vipTransfer: "نقل VIP",
    suitcases: "حقائب",
    selectCountryPlaceholder: "اختر دولة...",
    expediaPartner: "شريك إكسبيديا",
    bestRatesGuaranteed: "أفضل الأسعار مضمونة",
    luxuryHotelsAndSki: "فنادق فاخرة وتزلج",
    luxuryHotelsAndSkiSubtitle: "اختر وجهتك لاكتشاف فنادق شركائنا الحصرية. مقارنة في الوقت الفعلي.",
    loadingHotels: "جاري البحث عن أفضل الفنادق...",
    noHotelsAvailable: "لا توجد فنادق متاحة لهذه الوجهة.",
    serviceUnavailable: "الخدمة غير متوفرة مؤقتًا.",
    chooseAnotherDestination: "اختر وجهة أخرى",
    noImageAvailable: "لا توجد صورة",
    viewPrices: "عرض الأسعار",
    pleaseSelectDestination: "يرجى تحديد وجهة أعلاه",
    checkIn: "الوصول",
    checkOut: "المغادرة",
    loadingRates: "جاري البحث عن أفضل الأسعار...",
    ratesUnavailable: "الأسعار غير متوفرة لهذه التواريخ.",
    bookOnExpedia: "الحجز على إكسبيديا / Hotels.com",
    bookingRedirectDisclaimer: "عن طريق الحجز عبر هذا الرابط، سيتم إعادة توجيهك إلى شركائنا بتواريخ من {checkInDate} إلى {checkOutDate}.",
    carFilters: "مرشحات المركبات",
    maxPricePerDay: "أقصى سعر لليوم",
    transmission: "ناقل الحركة",
    make: "الصانع",
    auto: "أوتوماتيك",
    manual: "يدوي",
    destination: "الوجهة",
    countrySwitzerland: "سويسرا",
    countryEurope: "أوروبا (إقليمي)",
    countryFrance: "فرنسا",
    countryUae: "الإمارات",
    countryUsa: "الولايات المتحدة",
    days7: "7 أيام",
    days15: "15 يومًا",
    days30: "30 يومًا",
    unlimited: "غير محدود",
    luxuryHotelsAndAccommodations: "فنادق وإقامات فاخرة",
    stayInGenevaBest: "أقم في أرقى مؤسسات جنيف.",
    exclusiveExperiences: "تجارب حصرية",
    exclusiveExperiencesSubtitle: "لحظات لا تنسى، وصول VIP.",
  },
  ru: {
    home: 'Главная',
    deals: 'Акции',
    account: 'Аккаунт',
    mode: 'Режим',
    goodMorning: 'Доброе утро',
    goodAfternoon: 'Добрый день',
    goodEvening: 'Добрый вечер',
    heroTitle: 'Эксклюзивные предложения в Швейцарии',
    heroSubtitle: 'Ваш надежный гид по эксклюзивным предложениям',
    unlockOffers: 'Открыть предложения',
    hotelsTitle: "Роскошные отели",
    hotelsSubtitle: "Незабываемый отдых",
    hotelsBadge: "Скидки до -40%",
    carsTitle: "Престижные авто",
    carsSubtitle: "Партнеры: Sixt & Prestige",
    carsBadge: "Эксклюзивные тарифы",
    experiencesTitle: "Досуг и Открытия",
    experiencesSubtitle: "Музеи, Часы и Развлечения",
    experiencesBadge: "Туризм",
    transfersTitle: "Трансферы и Шофер",
    transfersSubtitle: "Аэропорт и Город",
    transfersBadge: "Лучшая цена",
    vipOnly: "VIP",
    vipSubtitle: "Специальные тарифы для участников",
    seeAll: "Показать все",
    todaysDeals: "ВЫБЕРИТЕ МЕСТОПОЛОЖЕНИЕ",
    testimonials: "Отзывы путешественников",
    verifiedMember: "Проверенный участник",
    promoTitle: "Скидка 100 CHF на первое бронирование",
    joinSave: "Присоединиться",
    searchPlaceholder: "Поиск...",
    discover: "Обзор",
    swissConcierge: "Швейцарский консьерж",
    guideToSwiss: "Ваш гид по Швейцарии",
    bestRentalDeals: "Лучшие предложения аренды",
    bestRentalDealsSubtitle: "Лучшие авто по лучшим ценам",
    generalExperiencesTitle: "Впечатления",
    generalExperiencesSubtitle: "Откройте Швейцарию",
    transferTitle: "Премиум трансферы из аэропорта",
    transferSubtitle: "Безупречное путешествие от прибытия до места назначения.",
    bookTransfer: "Заказать трансфер",
    klookBannerTitle: "Гарантия лучшей цены с Klook",
    klookBannerSubtitle: "Бронируйте через нашего партнера и экономьте до 60%",
    klookButton: "Проверить цены",
    instantConfirmation: "Мгновенное подтверждение",
    bookOnKlook: "Бронировать на Klook",
    viewFullInventory: "Посмотреть все отели",
    cantFindHotel: "Не нашли нужный отель?",
    searchOnKlook: "Искать все отели на Klook",
    pickupLocation: "Место посадки",
    dropoffLocation: "Назначение",
    oneWay: "В одну сторону",
    roundTrip: "Туда и обратно",
    findTransfer: "Найти трансфер",
    passengers: "Пассажиры",
    fixedPrice: "Фикс. цена",
    freeCancellation: "Беспл. отмена",
    professionalDriver: "Проф. водитель",
    selectDate: "Дата",
    selectTime: "Время",
    transferPageTitle: "Трансферы из аэропорта",
    transferPageSubtitle: "Надежные, роскошные трансферы с фиксированной ценой по всей Швейцарии.",
    ourFleet: "Наш автопарк",
    esimTitle: "Оставайтесь на связи",
    esimSubtitle: "Мгновенный интернет в Швейцарии и Европе.",
    selectDestination: "Выберите направление",
    dataPlans: "Тарифы данных",
    buyEsim: "Купить eSIM",
    instantActivation: "Мгновенная активация",
    globalCoverage: "200+ стран",
    bestRates: "На 18% дешевле",
    summary: "Итог",
    plan: "План",
    total: "Всего",

    // New keys
    exclusive: "Эксклюзив",
    comingSoon: "Скоро",
    contactOnWhatsApp: "Связаться в WhatsApp",
    whatsApp: "WhatsApp",
    whatsAppMessage: "Здравствуйте, Khaleex, я хотел бы получить информацию о ваших VIP-услугах.",
    needHelp: "Нужна помощь?",
    vipSupport: "VIP-поддержка 24/7",
    contactUs: "Связаться с нами",
    prestigeCars: "Престижные автомобили",
    admin: "Админ",
    loadingVehicles: "Загрузка автомобилей...",
    errorOccurred: "Произошла ошибка",
    errorLoadingVehicles: "Не удалось загрузить автомобили. Пожалуйста, попробуйте позже.",
    noVehiclesFound: "Автомобили, соответствующие вашим критериям, не найдены.",
    realTimeVehicles: "Автомобили доступны в режиме реального времени.",
    leisureAndDiscoveries: "Досуг и открытия",
    experiencesPageSubtitle: "Подборка культурных и туристических мероприятий для обогащения вашего пребывания в Швейцарии. Для наших эксклюзивных услуг (джеты, повара...) посетите раздел VIP.",
    loadingActivities: "Загрузка мероприятий...",
    errorLoadingExperiences: "Не удалось загрузить впечатления. Пожалуйста, попробуйте позже.",
    from: "от",
    perNight: "/ночь",
    showDetails: "Показать детали",
    hideDetails: "Скрыть детали",
    changeImage: "Изменить изображение",
    addImage: "Добавить изображение",
    imageNotAvailable: "Изображение недоступно",
    priceComparator: "Сравнение цен",
    bestOffer: "Лучшее предложение",
    seats: "мест",
    perDay: "/день",
    book: "Бронь",
    noImage: "Нет изображения",
    changeImageShort: "Изменить",
    rentalDetails: "Детали аренды",
    forVehicle: "Для автомобиля",
    pickupDate: "Дата получения",
    returnDate: "Дата возврата",
    pickupLocationLabel: "Место получения",
    pickupLocationPlaceholder: "например, Аэропорт Женевы",
    bookOnPartnerSite: "Бронировать на сайте партнера",
    redirectPartnerCar: "Вы будете перенаправлены на сайт нашего партнера для завершения аренды.",
    stayDetails: "Детали пребывания",
    forHotel: "Для отеля",
    checkInDate: "Дата заезда",
    checkOutDate: "Дата выезда",
    travelersCount: "Количество путешественников",
    finalizeBooking: "Завершить бронирование",
    redirectPartnerHotel: "Вы будете перенаправлены на сайт партнера для безопасного завершения бронирования.",
    myAccount: "Мой аккаунт",
    welcomeToKhaleex: "Добро пожаловать в Khaleex",
    loginToAccessVip: "Войдите, чтобы получить доступ к вашему VIP-профилю и эксклюзивным предложениям.",
    loginRegister: "Войти / Зарегистрироваться",
    byContinuingYouAgree: "Продолжая, вы соглашаетесь с нашими условиями обслуживания.",
    termsShort: "Условия",
    privacyShort: "Приватность",
    personalInfo: "Личная информация",
    paymentMethods: "Способы оплаты",
    notifications: "Уведомления",
    securityAndLogin: "Безопасность и вход",
    helpAndSupport: "Помощь и поддержка",
    legalAndCompliance: "Юридическая информация",
    legalNotice: "Правовая информация",
    logout: "Выйти",
    exclusiveServicesGeneva: "Эксклюзивные услуги в Женеве",
    rentPrestigeCar: "Арендовать престижный автомобиль",
    rentPrestigeCarSubtitle: "Откройте наш эксклюзивный автопарк и наслаждайтесь дорогой в стиле.",
    rentalPartners: "Наши партнеры по аренде в Женеве",
    exclusiveAtHomeServices: "Эксклюзивные услуги на дому",
    excursionsChamonix: "Экскурсии в Шамони",
    excursionsChamonixSubtitle: "Откройте для себя уникальные впечатления у подножия Монблана, вдохновленные лучшими предложениями на Airbnb и Klook. Бронируйте легко через нашего консьержа в WhatsApp.",
    reviews: "отзывов",
    inspiredBy: "Вдохновлено",
    fromPerPerson: "/чел.",
    filters: "Фильтры",
    maxPricePerNight: "Макс. цена за ночь",
    stars: "Звезды",
    amenities: "Удобства",
    reset: "Сбросить",
    apply: "Применить",
    serviceDetails: "Детали вашей услуги",
    forService: "Для услуги",
    date: "Дата",
    startTime: "Время начала",
    durationHours: "Продолжительность (в часах)",
    redirectPartnerService: "Вы будете перенаправлены для завершения вашего эксклюзивного бронирования.",
    publicPrice: "Общая цена",
    vipPrice: "VIP-цена",
    vipServices: "VIP-услуги",
    becomeVipMember: "Стать годовым VIP-членом",
    vipMemberDescription: "Экономьте до 30% на всех наших премиальных услугах: частные джеты, виллы, вертолеты и повара.",
    profitableFromFirstFlight: "Выгодно с первого полета.",
    subscribeAnnual: "Подписаться (1200 CHF/год)",
    exclusiveServicesOfTheMoment: "Эксклюзивные услуги на данный момент",
    vipDisclaimer: "*VIP-цены гарантированы для держателей карт Khaleex Black. Бронирования зависят от наличия и подтверждения нашей консьерж-службой.",
    legal: "Юридическая информация",
    support: "Поддержка",
    contactEmailLabel: "Электронная почта",
    exclusivePartner: "Эксклюзивный партнер",
    proChauffeurs: "Проф. шоферы",
    mercedesAndBmw: "Mercedes и BMW",
    meetAndGreet: "Встреча и проводы",
    vipTransfer: "VIP-трансфер",
    suitcases: "Чемоданы",
    selectCountryPlaceholder: "Выберите страну...",
    expediaPartner: "Партнер Expedia",
    bestRatesGuaranteed: "Гарантия лучших цен",
    luxuryHotelsAndSki: "Роскошные и горнолыжные отели",
    luxuryHotelsAndSkiSubtitle: "Выберите направление, чтобы открыть для себя наши эксклюзивные отели-партнеры. Сравнение в реальном времени.",
    loadingHotels: "Поиск лучших отелей...",
    noHotelsAvailable: "Нет доступных отелей для этого направления.",
    serviceUnavailable: "Сервис временно недоступен.",
    chooseAnotherDestination: "Выберите другое направление",
    noImageAvailable: "Нет изображения",
    viewPrices: "Посмотреть цены",
    pleaseSelectDestination: "Пожалуйста, выберите направление выше",
    checkIn: "Заезд",
    checkOut: "Выезд",
    loadingRates: "Поиск лучших тарифов...",
    ratesUnavailable: "Цены на эти даты недоступны.",
    bookOnExpedia: "Бронировать на Expedia / Hotels.com",
    bookingRedirectDisclaimer: "При бронировании по этой ссылке вы будете перенаправлены на сайты наших партнеров с датами с {checkInDate} по {checkOutDate}.",
    carFilters: "Фильтры автомобилей",
    maxPricePerDay: "Макс. цена в день",
    transmission: "Коробка передач",
    make: "Марка",
    auto: "Автомат",
    manual: "Механика",
    destination: "Направление",
    countrySwitzerland: "Швейцария",
    countryEurope: "Европа (регион)",
    countryFrance: "Франция",
    countryUae: "ОАЭ",
    countryUsa: "США",
    days7: "7 дней",
    days15: "15 дней",
    days30: "30 дней",
    unlimited: "Безлимитный",
    luxuryHotelsAndAccommodations: "Роскошные отели и размещение",
    stayInGenevaBest: "Остановитесь в лучших заведениях Женевы.",
    exclusiveExperiences: "Эксклюзивные впечатления",
    exclusiveExperiencesSubtitle: "Незабываемые моменты, VIP-доступ.",
  },
  fr: {
    home: 'Accueil',
    deals: 'Offres',
    account: 'Compte',
    mode: 'Mode',
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    heroTitle: 'Offres Suisses Exclusives pour les Voyageurs du Golfe',
    heroSubtitle: 'Votre guide de confiance pour des offres exclusives',
    unlockOffers: 'Débloquer les Offres Suisses Exclusives',
    hotelsTitle: "Hôtels de Luxe",
    hotelsSubtitle: "Séjours mémorables",
    hotelsBadge: "Jusqu'à -40%",
    carsTitle: "Voitures de Prestige",
    carsSubtitle: "Partenaires : Sixt & Prestige",
    carsBadge: "Tarifs Exclusifs",
    experiencesTitle: "Loisirs & Découvertes",
    experiencesSubtitle: "Musées, Montres & Fun",
    experiencesBadge: "Tourisme",
    transfersTitle: "Chauffeur & Transferts",
    transfersSubtitle: "Aéroport & Ville",
    transfersBadge: "Meilleur Prix",
    vipOnly: "Services ++",
    vipSubtitle: "Découvrez nos prestations exclusives",
    seeAll: "Voir tout",
    todaysDeals: "CHOISISSEZ VOTRE DESTINATION",
    testimonials: "Avis des voyageurs",
    verifiedMember: "Membre vérifié",
    promoTitle: "100 CHF de remise sur votre première réservation",
    joinSave: "Rejoindre & Économiser",
    searchPlaceholder: "Rechercher...",
    discover: "Découvrir",
    swissConcierge: "Conciergerie Suisse",
    guideToSwiss: "Votre guide en Suisse",
    bestRentalDeals: "Meilleures Offres de Location",
    bestRentalDealsSubtitle: "Conduisez le meilleur pour moins cher",
    generalExperiencesTitle: "Expériences",
    generalExperiencesSubtitle: "Découvrez la Suisse",
    transferTitle: "Transferts Aéroport Premium",
    transferSubtitle: "Voyage fluide et luxueux de l'arrivée à votre destination. Meilleurs tarifs garantis.",
    bookTransfer: "Réserver un Transfert",
    klookBannerTitle: "Meilleur Prix Garanti avec Klook",
    klookBannerSubtitle: "Réservez votre séjour via notre partenaire officiel et économisez jusqu'à 60%",
    klookButton: "Voir les Tarifs",
    instantConfirmation: "Confirmation Instantanée",
    bookOnKlook: "Réserver sur Klook",
    viewFullInventory: "Voir l'Inventaire Complet",
    cantFindHotel: "Vous ne trouvez pas l'hôtel que vous cherchez ?",
    searchOnKlook: "Rechercher tous les hôtels sur Klook",
    pickupLocation: "Lieu de prise en charge",
    dropoffLocation: "Destination",
    oneWay: "Aller simple",
    roundTrip: "Aller-retour",
    findTransfer: "Trouver un Transfert",
    passengers: "Passagers",
    fixedPrice: "Prix Fixe",
    freeCancellation: "Annulation Gratuite",
    professionalDriver: "Chauffeur Pro",
    selectDate: "Date",
    selectTime: "Heure",
    transferPageTitle: "Transferts Aéroport & Chauffeur",
    transferPageSubtitle: "Transferts fiables, luxueux et à prix fixe dans toute la Suisse.",
    ourFleet: "Notre Flotte",
    esimTitle: "Voyagez Connecté",
    esimSubtitle: "Accès internet instantané en Suisse & Europe.",
    selectDestination: "Choisissez la Destination",
    dataPlans: "Forfaits de Données",
    buyEsim: "Acheter mon eSIM",
    instantActivation: "Activation Instantanée",
    globalCoverage: "200+ Destinations",
    bestRates: "18% Moins Cher",
    summary: "Résumé",
    plan: "Forfait",
    total: "Total",
    
    // New keys
    exclusive: "Exclusif",
    comingSoon: "Bientôt disponible",
    contactOnWhatsApp: "Contacter sur WhatsApp",
    whatsApp: "WhatsApp",
    whatsAppMessage: "Bonjour Khaleex, je souhaiterais avoir des informations sur vos services VIP.",
    needHelp: "Besoin d'aide ?",
    vipSupport: "Support VIP 24/7",
    contactUs: "Nous Contacter",
    prestigeCars: "Voitures de Prestige",
    admin: "Admin",
    loadingVehicles: "Chargement des véhicules...",
    errorOccurred: "Une erreur est survenue",
    errorLoadingVehicles: "Impossible de charger les véhicules. Veuillez réessayer plus tard.",
    noVehiclesFound: "Aucun véhicule ne correspond à vos critères.",
    realTimeVehicles: "Véhicules disponibles en temps réel.",
    leisureAndDiscoveries: "Loisirs et Découvertes",
    experiencesPageSubtitle: "Une sélection d'activités culturelles et touristiques pour enrichir votre séjour en Suisse. Pour nos services exclusifs (Jets, Chefs...), visitez la section VIP.",
    loadingActivities: "Chargement des activités...",
    errorLoadingExperiences: "Impossible de charger les expériences. Veuillez réessayer plus tard.",
    from: "dès",
    perNight: "/nuit",
    showDetails: "Voir les détails",
    hideDetails: "Masquer les détails",
    changeImage: "Changer l'image",
    addImage: "Ajouter une image",
    imageNotAvailable: "Image non disponible",
    priceComparator: "Comparateur de Prix",
    bestOffer: "Meilleure Offre",
    seats: "places",
    perDay: "/jour",
    book: "Réserver",
    noImage: "Pas d'image",
    changeImageShort: "Changer",
    rentalDetails: "Détails de votre Location",
    forVehicle: "Pour le véhicule",
    pickupDate: "Date de prise en charge",
    returnDate: "Date de retour",
    pickupLocationLabel: "Lieu de prise en charge",
    pickupLocationPlaceholder: "ex: Genève Aéroport",
    bookOnPartnerSite: "Réserver sur le site partenaire",
    redirectPartnerCar: "Vous allez être redirigé vers le site de notre partenaire pour finaliser la location.",
    stayDetails: "Détails de votre Séjour",
    forHotel: "Pour l'hôtel",
    checkInDate: "Date d'arrivée",
    checkOutDate: "Date de départ",
    travelersCount: "Nombre de voyageurs",
    finalizeBooking: "Finaliser la réservation",
    redirectPartnerHotel: "Vous allez être redirigé chez notre partenaire pour finaliser votre réservation en toute sécurité.",
    myAccount: "Mon Compte",
    welcomeToKhaleex: "Bienvenue sur Khaleex",
    loginToAccessVip: "Connectez-vous pour accéder à votre profil VIP et débloquer des offres exclusives.",
    loginRegister: "Se Connecter / S'inscrire",
    byContinuingYouAgree: "En continuant, vous acceptez nos conditions d'utilisation.",
    termsShort: "CGU",
    privacyShort: "Confidentialité",
    personalInfo: "Informations Personnelles",
    paymentMethods: "Moyens de Paiement",
    notifications: "Notifications",
    securityAndLogin: "Sécurité & Connexion",
    helpAndSupport: "Aide & Support",
    legalAndCompliance: "Légal & Conformité",
    legalNotice: "Mentions Légales",
    logout: "Se Déconnecter",
    exclusiveServicesGeneva: "Services Exclusifs à Genève",
    rentPrestigeCar: "Louer une voiture de prestige",
    rentPrestigeCarSubtitle: "Découvrez notre flotte exclusive et profitez de la route avec style.",
    rentalPartners: "Nos partenaires de location à Genève",
    exclusiveAtHomeServices: "Services Exclusifs à Domicile",
    excursionsChamonix: "Excursions à Chamonix",
    excursionsChamonixSubtitle: "Découvrez des expériences uniques au pied du Mont Blanc, inspirées des meilleures offres Airbnb et Klook. Réservez facilement via notre conciergerie WhatsApp.",
    reviews: "avis",
    inspiredBy: "Inspiré de",
    fromPerPerson: "/pers.",
    filters: "Filtres",
    maxPricePerNight: "Prix maximum par nuit",
    stars: "Étoiles",
    amenities: "Équipements",
    reset: "Réinitialiser",
    apply: "Appliquer",
    serviceDetails: "Détails de votre Prestation",
    forService: "Pour la prestation",
    date: "Date",
    startTime: "Heure de début",
    durationHours: "Durée (en heures)",
    redirectPartnerService: "Vous allez être redirigé pour finaliser votre réservation exclusive.",
    publicPrice: "Prix Public",
    vipPrice: "Prix VIP",
    vipServices: "Services VIP",
    becomeVipMember: "Devenez Membre VIP Annuel",
    vipMemberDescription: "Économisez jusqu'à 30% sur tous nos services premium : Jets Privés, Villas, Hélicoptères et Chefs.",
    profitableFromFirstFlight: "Rentabilisé dès le premier vol.",
    subscribeAnnual: "Souscrire (1200 CHF/an)",
    exclusiveServicesOfTheMoment: "Services Exclusifs du Moment",
    vipDisclaimer: "*Les prix VIP sont garantis pour les détenteurs de la carte Khaleex Black. Les réservations sont soumises à disponibilité et confirmation par notre service de conciergerie.",
    legal: "Légal",
    support: "Support",
    contactEmailLabel: "Email",
    exclusivePartner: "Partenaire Exclusif",
    proChauffeurs: "Chauffeurs Pro",
    mercedesAndBmw: "Mercedes & BMW",
    meetAndGreet: "Accueil Personnalisé",
    vipTransfer: "Transfert VIP",
    suitcases: "Valises",
    selectCountryPlaceholder: "Sélectionnez un pays...",
    expediaPartner: "Partenaire Expedia",
    bestRatesGuaranteed: "Meilleurs Tarifs Garantis",
    luxuryHotelsAndSki: "Hôtels de Luxe & Ski",
    luxuryHotelsAndSkiSubtitle: "Sélectionnez votre destination pour découvrir nos hôtels partenaires exclusifs. Comparaison en temps réel.",
    loadingHotels: "Recherche des meilleurs hôtels...",
    noHotelsAvailable: "Aucun hôtel disponible pour cette destination.",
    serviceUnavailable: "Service temporairement indisponible.",
    chooseAnotherDestination: "Choisir une autre destination",
    noImageAvailable: "Aucune image",
    viewPrices: "Voir les prix",
    pleaseSelectDestination: "Veuillez sélectionner une destination ci-dessus",
    checkIn: "Arrivée",
    checkOut: "Départ",
    loadingRates: "Recherche des meilleurs tarifs...",
    ratesUnavailable: "Tarifs non disponibles pour ces dates.",
    bookOnExpedia: "Réserver sur Expedia / Hotels.com",
    bookingRedirectDisclaimer: "En réservant via ce lien, vous serez redirigé chez nos partenaires avec les dates du {checkInDate} au {checkOutDate}.",
    carFilters: "Filtres de Véhicules",
    maxPricePerDay: "Prix maximum par jour",
    transmission: "Boîte de vitesse",
    make: "Marque",
    auto: "Auto",
    manual: "Manuelle",
    destination: "Destination",
    countrySwitzerland: "Suisse",
    countryEurope: "Europe (Régional)",
    countryFrance: "France",
    countryUae: "EAU",
    countryUsa: "USA",
    days7: "7 Jours",
    days15: "15 Jours",
    days30: "30 Jours",
    unlimited: "Illimité",
    luxuryHotelsAndAccommodations: "Hôtels & Hébergements de Luxe",
    stayInGenevaBest: "Séjournez dans les plus beaux établissements de Genève.",
    exclusiveExperiences: "Expériences Exclusives",
    exclusiveExperiencesSubtitle: "Des moments inoubliables, accès VIP.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  direction: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const [direction, setDirection] = useState<'ltr' | 'rtl'>('ltr');

  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
    setDirection(dir);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, direction }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};